### PR TITLE
fix issue 13

### LINKED ISSUE #13: Error: function ffmpeg.libavformat.avformat.AVIndexEntry.flags(int v) cannot be overloaded with another extern(C) #121
see https://github.com/libmir/dcv/issues/121

### PR DESCRIPTION
**Pull request by timotheecour**
fix https://github.com/ljubobratovicrelja/ffmpeg-d/issues/13

### CODE REVIEW

**Comment by ljubobratovicrelja** [comment]
Thank you @timotheecour! @complistic-gaff this fix seems to be affecting all 3.x branches, so should probably be merged in 3.0 and 3.1 branches, as well as in master, right?

**Comment by DavidBennettPIO** [comment]
I haven't had time to look into this properly yet, but it looks to be related to a regression/improvement on 2.078.2?
https://issues.dlang.org/show_bug.cgi?id=18385

I would have thought it would effect the 2.8 branch also?

In any case the workaround seems simple enough.

I think a C int is 4 bytes (same as D) in all the platforms/compilers we care about?

**Review by DavidBennettPIO — APPROVED** [review]
Looks sane enough, and allows it to compile so I think it's a good workaround.

**Comment by ljubobratovicrelja** [comment]
Awesome, tnx @complistic-gaff! OK, merging this right now into master, and will release a patch for 3.1, since master is in sync with that branch. I'll try and merge this into version branches on weekend, and make 2.8 and 3.0 releases.

**Pull request merged**
