### PR TITLE
Updated source for v4.4.

### PR DESCRIPTION
**Pull request by ljubobratovicrelja**
dstep convert, done by Ferhat Kurtulmuş.

This branch is to be merged into master, but **not deleted**, to be kept for future backwards compatibility.

### CODE REVIEW

**Comment by ljubobratovicrelja** [comment]
Thanks so much for your inputs @aferust! I spent a lot of time during the weekend to set up dev environment, and remembered what hell it is with D - on Windows, compiling C libraries like FFmpeg is horrible, on macos lldb is still not working properly out of the box, and for gdb you have to set up some certificates, which completely destroyed all my willpower to do this. I'll probably end up with setting up ubuntu machine, since I remember everything functioning 100% there back in the day. Any hint in this regard is more then welcome, it doesn't really seem D has moved an inch since I left (3-4 years ago) in these things, which is quite depressing and rather embarrassing for them.

Anyhow, examples are failing for me, but I didn't manage to set up the debugger, so I am yet to understand why. Until that remains the issue, we shouldn't merge this. If by some chance this is something you are willing to look into, please do. In either case, I am continuing with setting up my environment asap, so I can do stuff properly in the future.

**Comment by aferust** [comment]
Dear Relja, I am writing on my mobile phone. I will send you ffmpeg compiled libs (win10) when I get back to my office. I need your email.

**Review by ljubobratovicrelja — COMMENTED** [review]
Wait, now I took a closer look at your edits. We have a misunderstanding here - I wasn't planning on this to be purely DCV branch, but rather a proper FFmpeg version 4.4 bindings for general use. Please revert the deletion of those aspects - tests and examples should remain, so should all the comments that are put there in the first place.

After all, we want this to be merged into master, as it was practice so far with ffmpeg-d, and even if its not used that much, I don't want to pollute the original idea of this library and steer it towards DCV.

Sorry for this, it was a miscommunication for sure.

**Comment by ljubobratovicrelja** [comment]
> Dear Relja, I am writing on my mobile phone. I will send you ffmpeg compiled libs (win10) when I get back to my office. I need your email.

That would be of huge help! Thanks!
email: ljubobratovic.relja@gmail.com

**Comment by ljubobratovicrelja** [comment]
@aferust the `encode_example` seems to be working, however we do get a low of deprecation warnings (even errors crashing the program if we don't [enable experimental features](https://github.com/ljubobratovicrelja/ffmpeg-d/pull/15/commits/6eec0f0e96685d086b6d4a541939a2a767784c61#diff-cc6caa1f8153cd37db7d56c85bbaa3785f2be0d07c684fb0910ba1ce5e38f820R271)).

These are the warnings I'm seeing though honestly, I am feeling like Alice in Wonderland trying to resolve those. Do you have more understanding of those, and of ffmpeg API to know what to change?
image

Also, I would be OK to leave this example unattended like this, and switch our focus to DCV videoio module as soon as possible. So if you are OK, I would merge this as such, and then if there's errors we encounter on DCV end, we can make another PR to fix it here at the source.

**Pull request merged**
